### ISSUE TITLE
Your production app will leak your gooey api key.

### ISSUE THREAD

**Issue by AndKenneth** [eugenepokalyuk/next-generate-qr#1]
You've marked it NEXT_PUBLIC and are using it in client code. It would be trivial for anyone to extract this and use it for their own purposes.

**Comment by AndKenneth** [comment]
@eugenepokalyuk I see you tried to fix it by moving your code to another file. Unfortunately it's still client side code. If you mark this file as 'use server', it should turn the function into a server action which can be called (mostly) the same way.

https://github.com/eugenepokalyuk/next-generate-qr/blob/main/utils/api.tsx

lmk if you have any questions, I just stumbled upon this wouldn't want someone to rack up huge bills on that key.

**Comment by eugenepokalyuk** [comment]
I fixed the problem with using the API key from the client side by moving the code to a separate file and using environment variables from env.local without using 'use server'. Thanks for your consideration and concern for data security! 🛡️🔒

**Comment by AndKenneth** [comment]
I'd still recommend removing NEXT_PUBLIC from your api key to make sure it can never end up on the client.

You can do the same thing with any server code by importing the 'server-only' package into any file that runs code that needs to be in a trusted environment. It will cause an error if it is imported by a client component.

https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#keeping-server-only-code-out-of-the-client-environment
